<?php
$z[0]=Array("arcurl","",29,44);
$z[1]=Array("title","",53,67);
$z[2]=Array("picname","",79,95);
$z[3]=Array("title","",168,182);
$z[4]=Array("title","",189,203);
$z[5]=Array("arcurl","",262,277);
$z[6]=Array("title","",286,300);
$z[7]=Array("title","",302,316);
$z[8]=Array("pubdate","",355,402);
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("description","",442,492);
$z[9][4]['function']="cn_substr(@me,100)";

?>