<div class="fl n1"> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" onerror="this.src='images/nopic.gif';" width="291" height="218" title="[field:title/]" alt="[field:title/]"/></a>
        <div class="n_1">
          <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
          <div class="date">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
          <div class="contents">[field:description function='cn_substr(@me,100)'/]...</div>
        </div>
        <div class="clear"></div>
      </div>