<div class="news_1"> <a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" onerror="this.src='/images/nopic.gif';" width="291" height="218" alt="[field:title/]" title="[field:title/]"> </a>
      <div class="intro">
        <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
        <div class="date">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
        <div class="contents">[field:info/]...</div>
      </div>
    </div>