<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",340,369);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",409,467);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1136,1171);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1463,1521);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("field","",1618,1647);
$z[6][4]['name']="position";
$z[7]=Array("field","",1772,1793);
$z[7][4]['name']="content";
$z[8]=Array("arclist","\r\n          <div class=\"lkson\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"pic\"><img src=\"[field:picname/]\" onerror=\"this.src='/images/nopic.gif';\" width=\"288\" height=\"216\" alt=\"[field:title/]\" title=\"[field:title/]\"/></a><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"text\">[field:title/]</a></div>\r\n          ",2304,2694);
$z[8][4]['row']="7";
$z[8][4]['titlelen']="32";
$z[8][4]['typeid']="2";
$z[9]=Array("include","",2838,2875);
$z[9][4]['filename']="footer.htm";

?>