<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1124,1159);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1452,1510);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("field","",1607,1636);
$z[6][4]['name']="position";
$z[7]=Array("field","",1741,1760);
$z[7][4]['name']="title";
$z[8]=Array("field","",1842,1860);
$z[8][4]['name']="body";
$z[9]=Array("prenext","",1940,1965);
$z[9][4]['get']="pre";
$z[10]=Array("prenext","",2001,2027);
$z[10][4]['get']="next";
$z[11]=Array("type","<a href=\"[field:typelink/]\" title=\"返回列表\">返回列表</a>",2062,2150);
$z[12]=Array("arclist","\r\n          <div class=\"lkson\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"pic\"><img src=\"[field:picname/]\" onerror=\"this.src='/images/nopic.gif';\" width=\"288\" height=\"216\" alt=\"[field:title/]\" title=\"[field:title/]\"/></a><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"text\">[field:title/]</a></div>\r\n          ",2670,3060);
$z[12][4]['row']="7";
$z[12][4]['titlelen']="32";
$z[12][4]['typeid']="2";
$z[13]=Array("include","",3204,3241);
$z[13][4]['filename']="footer.htm";

?>