<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1124,1159);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1560,1589);
$z[5][4]['name']="position";
$z[6]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",1712,1895);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='hover'>~typename~</a>";
$z[7]=Array("field","",1995,2014);
$z[7][4]['name']="title";
$z[8]=Array("field","",2085,2137);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("field","",2190,2210);
$z[9][4]['name']="writer";
$z[10]=Array("field","",2293,2311);
$z[10][4]['name']="body";
$z[11]=Array("prenext","",2385,2410);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2444,2470);
$z[12][4]['get']="next";
$z[13]=Array("type","<a href=\"[field:typelink/]\" title=\"返回列表\">返回列表</a>",2503,2591);
$z[14]=Array("arclist","\r\n          <div class=\"lkson\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"pic\"><img src=\"[field:picname/]\" onerror=\"this.src='/images/nopic.gif';\" width=\"288\" height=\"216\" alt=\"[field:title/]\" title=\"[field:title/]\"/></a><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"text\">[field:title/]</a></div>\r\n          ",3097,3487);
$z[14][4]['row']="7";
$z[14][4]['titlelen']="32";
$z[14][4]['typeid']="2";
$z[15]=Array("include","",3631,3668);
$z[15][4]['filename']="footer.htm";

?>