<?php
$z[0]=Array("flink","  [field:link /] <a>|</a> ",70,156);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",329,355);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",467,493);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",502,528);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",795,821);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",924,948);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\" >[field:typename/]</a><a>|</a> ",1255,1389);
$z[6][4]['type']="top";
$z[6][4]['row']="10";

?>