<?php
$z[0]=Array("global","",195,221);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",228,254);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",351,377);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",469,495);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",502,528);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",622,887);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>