<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1138,1173);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1460,1518);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("field","",1615,1644);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n      <div class=\"s1\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" onerror=\"this.src='/images/nopic.gif';\" width=\"288\" height=\"216\" title=\"[field:title/]\" alt=\"[field:title/]\"/> </a> <span><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></span> </div>\r\n      ",1736,2086);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",2166,2212);
$z[8][4]['listitem']="index,end,pre,next";
$z[9]=Array("include","",2396,2433);
$z[9][4]['filename']="footer.htm";

?>